version: '3.10'

services:
  python-flask-app:
    # It doesn't start until the mysql service is up
    depends_on:
      - mysql-flask-app
    image: contactsapp
    container_name: python-flask-app-container
    ports:
      - 3000:3000
  
  mysql-flask-app:
      image: mysql:8.0
      container_name: mysql-flask-app-container
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 12345
      volumes:
        # Run the init.sql when starting mysql
        - ./data/contacts.sql:/docker-entrypoint-initdb.d/init.sql
